---
- name: Configure VoIP VPS
  hosts: voip-vps
  connection: local
  gather_facts: true

  vars_files:
    - group_vars/vault.yml

  pre_tasks:
    - name: Require root
      ansible.builtin.assert:
        that:
          - ansible_user_uid == 0
        fail_msg: "Run deployment as root."

  roles:
    - role: base
      tags:
        - base

    - role: awg
      tags:
        - awg

    - role: firewall
      tags:
        - firewall

    - role: coturn
      tags:
        - coturn

    - role: sip_watch
      tags:
        - watcher

    - role: fail2ban
      tags:
        - fail2ban
